settings:
  title: 'The NAP Platform Status'
  url: 'https://status.nap.social' # used for Slack messages
  logo: logo-144x144.png # image in ./public/ folder
  daysInHistogram: 90 # number of days you want to display in histogram
  collectResponseTimes: true # collects avg response times from CRON locations

  allmonitorsOperational: '所有服務正常運作 (All Systems Operational)'
  notAllmonitorsOperational: '部分服務受阻 (Not All Systems Operational)'
  monitorLabelOperational: '服務中 (Operational)'
  monitorLabelNotOperational: '服務受阻 (Not Operational)'
  monitorLabelNoData: '沒有資料 (No data)'
  dayInHistogramNoData: '沒有資料 (No data)'
  dayInHistogramOperational: '一切正常 (All good)'
  dayInHistogramNotOperational: '件服務異常 (incident(s))' # xx incident(s) recorded

monitors:
  - id: nap-social # unique identifier
    name: nap.social
    url: 'https://nap.social' # URL to fetch
    method: GET # default=GET
    expectStatus: 200 # operational status, default=200
    followRedirect: false # should fetch follow redirects, default=false
    linkable: true # allows the title to be a link, default=true

  - id: nap-api
    name: "nap.social API"
    url: "https://nap.social/api/v2/instance"
    method: GET
    expectStatus: 200 # operational status, default=200
    followRedirect: false # should fetch follow redirects, default=false
    linkable: false # allows the title to be a link, default=true

  - id: nap-shorter
    name: "NAP Shorter"
    url: "https://nap.tw"
    method: GET
    expectStatus: 200 # operational status, default=200
    followRedirect: false # should fetch follow redirects, default=false
    linkable: true # allows the title to be a link, default=true
