settings:
  title: "Status Page"
  logo: logo-192x192.png
  daysInHistogram: 90

  allmonitorsOperational: "All Systems Operational"
  notAllmonitorsOperational: "Not All Systems Operational"
  monitorLabelOperational: "Operational"
  monitorLabelNotOperational: "Not great not terrible"
  monitorLabelNoData: "No data"


monitors:
  - id: kiwi-com-homepage
    name: Kiwi.com homepage
    description: Kiwi.com en homepage
    url: 'https://www.kiwi.com/en/'
    method: GET
    expectStatus: 200
    followRedirect: false

  - id: eidam-dev
    name: Cheesy Status Page
    description: 'status-page.eidam.dev'
    url: 'https://status-page.eidam.dev/'
    method: GET
    expectStatus: 200

  - id: google-com
    name: Google.com
    description: Google homepage
    url: 'https://www.google.com'
    method: GET
    expectStatus: 200

  - id: cf-workers-status-page
    name: This Workers Status Page project made public
    description: /shrug
    url: 'https://github.com/adam-janis/cf-workers-status-page'
    method: GET
    expectStatus: 200

  - id: kiwicomapi-cn
    name: Some other site
    description: Is this done yet?
    url: 'http://kiwicomapi.cn/'
    method: GET
    expectStatus: 200

  - id: testy-testy
    name: Testy testy
    description: Something /shrug
    url: 'http://kiwicomapiiii.cn/'
    method: GET
    expectStatus: 200

  - id: hello-world
    name: Hello World
    url: 'http://cnn.cn/'
    method: GET
    expectStatus: 200





  - id: eidam-dev-2
    name: Eidam.dev
    description: 'Eidam.dev homepage, there is none'
    url: 'https://eidam.dev'
    method: GET
    expectStatus: 403

  - id: google-com-2
    name: Google.com
    description: Google homepage
    url: 'https://www.google.com'
    method: GET
    expectStatus: 200

  - id: cf-workers-status-page-2
    name: This Workers Status Page project made public
    description: /shrug
    url: 'https://github.com/adam-janis/cf-workers-status-page'
    method: GET
    expectStatus: 200

  - id: kiwicomapi-cn-2
    name: Kiwi.com API CN
    description: Is this done yet?
    url: 'http://kiwicomapi.cn/'
    method: GET
    expectStatus: 200

  - id: testy-testy-2
    name: Testy testy
    description: Something /shrug
    url: 'http://kiwicomapiiii.cn/'
    method: GET
    expectStatus: 200

  - id: hello-world-2
    name: Hello World
    url: 'http://cnn.cn/'
    method: GET
    expectStatus: 200



  - id: eidam-dev-22
    name: Eidam.dev
    description: 'Eidam.dev homepage, there is none'
    url: 'https://eidam.dev'
    method: GET
    expectStatus: 403

  - id: google-com-22
    name: Google.com
    description: Google homepage
    url: 'https://www.google.com'
    method: GET
    expectStatus: 200

  - id: cf-workers-status-page-22
    name: This Workers Status Page project made public
    description: /shrug
    url: 'https://github.com/adam-janis/cf-workers-status-page'
    method: GET
    expectStatus: 200

  - id: kiwicomapi-cn-22
    name: Kiwi.com API CN
    description: Is this done yet?
    url: 'http://kiwicomapi.cn/'
    method: GET
    expectStatus: 200

  - id: testy-testy-22
    name: Testy testy
    description: Something /shrug
    url: 'http://kiwicomapiiii.cn/'
    method: GET
    expectStatus: 200

  - id: hello-world-22
    name: Hello World
    url: 'http://cnn.cn/'
    method: GET
    expectStatus: 200


  - id: eidam-dev-333
    name: Eidam.dev
    description: 'Eidam.dev homepage, there is none'
    url: 'https://eidam.dev'
    method: GET
    expectStatus: 403

  - id: google-com-333
    name: Google.com
    description: Google homepage
    url: 'https://www.google.com'
    method: GET
    expectStatus: 200

  - id: cf-workers-status-page-333
    name: This Workers Status Page project made public
    description: /shrug
    url: 'https://github.com/adam-janis/cf-workers-status-page'
    method: GET
    expectStatus: 200

  - id: kiwicomapi-cn-333
    name: Kiwi.com API CN
    description: Is this done yet?
    url: 'http://kiwicomapi.cn/'
    method: GET
    expectStatus: 200

  - id: testy-testy-333
    name: Testy testy
    description: Something /shrug
    url: 'http://kiwicomapiiii.cn/'
    method: GET
    expectStatus: 200

  - id: hello-world-333
    name: Hello World
    url: 'http://cnn.cn/'
    method: GET
    expectStatus: 200










  - id: 25-eidam-dev
    name: Eidam.dev
    description: 'Eidam.dev homepage, there is none'
    url: 'https://eidam.dev'
    method: GET
    expectStatus: 403

  - id: 25-google-com
    name: Bing.com
    description: Bing homepage
    url: 'https://www.google.com'
    method: GET
    expectStatus: 200

  - id: 25-cf-workers-status-page
    name: This Workers Status Page project made public
    description: /shrug
    url: 'https://github.com/adam-janis/cf-workers-status-page'
    method: GET
    expectStatus: 200

  - id: 25-kiwicomapi-cn
    name: Kiwi.com API CN
    description: Is this done yet?
    url: 'http://kiwicomapi.cn/'
    method: GET
    expectStatus: 200

  - id: 25-testy-testy
    name: Testy testy
    description: Something /shrug
    url: 'http://kiwicomapiiii.cn/'
    method: GET
    expectStatus: 200

  - id: 25-hello-world
    name: Hello World
    url: 'http://cnn.cn/'
    method: GET
    expectStatus: 200





  - id: 25-eidam-dev-2
    name: Seznam.cz
    description: 'Just seznam'
    url: 'https://eidam.dev'
    method: GET
    expectStatus: 403

  - id: 25-google-com-2
    name: Google.com
    description: Google homepage
    url: 'https://www.google.com'
    method: GET
    expectStatus: 200

  - id: 25-cf-workers-status-page-2
    name: This Workers Status Page project made public
    description: /shrug
    url: 'https://github.com/adam-janis/cf-workers-status-page'
    method: GET
    expectStatus: 200

  - id: 25-kiwicomapi-cn-2
    name: Kiwi.com API CN
    description: Is this done yet?
    url: 'http://kiwicomapi.cn/'
    method: GET
    expectStatus: 200

  - id: 25-testy-testy-2
    name: Testy testy
    description: Something /shrug
    url: 'http://kiwicomapiiii.cn/'
    method: GET
    expectStatus: 200

  - id: 25-hello-world-2
    name: Hello World
    url: 'http://cnn.cn/'
    method: GET
    expectStatus: 200



  - id: 25-eidam-dev-22
    name: Eidam.dev
    description: 'Eidam.dev homepage, there is none'
    url: 'https://eidam.dev'
    method: GET
    expectStatus: 403

  - id: 25-google-com-22
    name: Google.com
    description: Google homepage
    url: 'https://www.google.com'
    method: GET
    expectStatus: 200

  - id: 25-cf-workers-status-page-22
    name: This Workers Status Page project made public
    description: /shrug
    url: 'https://github.com/adam-janis/cf-workers-status-page'
    method: GET
    expectStatus: 200

  - id: 25-kiwicomapi-cn-22
    name: Something totally different
    description: Is this done yet?
    url: 'http://kiwicomapi.cn/'
    method: GET
    expectStatus: 200

  - id: 25-testy-testy-22
    name: Testy testy
    description: Something /shrug
    url: 'http://kiwicomapiiii.cn/'
    method: GET
    expectStatus: 200

  - id: 25-hello-world-22
    name: Hello World
    url: 'http://cnn.cn/'
    method: GET
    expectStatus: 200


  - id: 25-eidam-dev-333
    name: Eidam.dev
    description: 'Eidam.dev homepage, there is none'
    url: 'https://eidam.dev'
    method: GET
    expectStatus: 403

  - id: 25-google-com-333
    name: Google.com
    description: Google homepage
    url: 'https://www.google.com'
    method: GET
    expectStatus: 200

  - id: 25-cf-workers-status-page-333
    name: This Workers Status Page project made public
    description: /shrug
    url: 'https://github.com/adam-janis/cf-workers-status-page'
    method: GET
    expectStatus: 200

  - id: 25-kiwicomapi-cn-333
    name: Kiwi.com API CN
    description: Is this done yet?
    url: 'http://kiwicomapi.cn/'
    method: GET
    expectStatus: 200

  - id: 25-testy-testy-333
    name: Testy testy
    description: Something /shrug
    url: 'http://kiwicomapiiii.cn/'
    method: GET
    expectStatus: 200

  - id: 25-hello-world-333
    name: Hello World
    url: 'http://cnn.cn/'
    method: GET
    expectStatus: 200

  - id: 25-hello-world-333
    name: Hello World
    url: 'http://cnn.cn/'
    method: GET
    expectStatus: 200

